apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: app
        image: mnginx  # Green Version
        ports:
        - containerPort: 80
